Changes to work properly under SELinux-enabled systems.  Both builds as well as runtime tasks work properly with attached storage and volume mounts.

diff --git a/baseimage/setup/apps/bin/clone-apps b/baseimage/setup/apps/bin/clone-apps
--- a/baseimage/setup/apps/bin/clone-apps
+++ b/baseimage/setup/apps/bin/clone-apps
@@ -23,8 +23,10 @@ if [ "${DESTPATH#/}" == "${DESTPATH}" ]; then
 fi
 
 if [ -e "$DESTPATH" ]; then
-  echo "Error: already exists, $DESTPATH"
-  exit 1
+  if [ "$(ls $DESTPATH)" != "" ]; then
+    echo "Error: already exists and is not empty, $DESTPATH"
+    exit 1
+  fi
 fi
 
 # Clone the actual directory
