Many changes, refactoring, improvements: - Assured that all images support get-help and get-launcher. - Created a template-based approach to launcher and help generation so   that derivative images can completely customize how they export their   configuration needs and startup scripts. - Formalized CONFIG_ variables and put them in 005-config.conf - Improved template expansion and made syntax consistent across   various uses. - Added tests for --tasks like get-launcher and get-chaplocal - Added SSL suport to lemp image.

diff --git a/bin/test-driver b/bin/test-driver
--- a/bin/test-driver
+++ b/bin/test-driver
@@ -3,7 +3,8 @@
 
 function relpath() { python -c "import os; print(os.path.relpath('$1', '$2' or os.curdir))"; }
 
-TESTDIR=$1
+TESTDIR=$(readlink -f $1)
+TMPDIR=$TESTDIR/_temp_
 IMAGE_NAME=$2
 LOGDIR=$3
 LOGFILE=$LOGDIR/$IMAGE_NAME.log
@@ -11,6 +12,11 @@ export EL_TEST_IMAGE=chapdev/$IMAGE_NAME
 
 if [ ! -d $TESTDIR ]; then
    exit
+fi
+
+if [ -e $TMPDIR ]; then
+   echo "Can't continue... $TMPDIR already exists."
+   exit 1
 fi
 
 if [ "`which expect-lite`" == "" ]; then
@@ -22,15 +28,16 @@ mkdir -p $LOGDIR
 
 (
   exitcode=0
-  cd $TESTDIR
   rm -rf $LOGFILE
-  for sf in $( find . -type f -executable \! -name '*~' ); do
-    echo "Running $IMAGE_NAME $sf"
-    echo "Running $IMAGE_NAME $sf" >>$LOGFILE
+  for sf in $( find $TESTDIR -type f -executable \! -name '*~' ); do
+    mkdir $TMPDIR; cd $TMPDIR
+    echo "Running $IMAGE_NAME - ${sf/*\//}"
+    echo "Running $IMAGE_NAME - $sf" >>$LOGFILE
     if ! $sf >>$LOGFILE 2>&1; then
       echo "TEST FAILED: $IMAGE_NAME $sf (see $(relpath $LOGFILE.err $TOPLEV_DIR))"
       exitcode=2
     fi
+    cd $TESTDIR; rm -rf $TMPDIR
   done
   if [ $exitcode == 0 ]; then
       echo "Tests passed for $IMAGE_NAME"
